In [1]:
import numpy as np

# **Matriks sebagai hasil dari Multiplikasi Produk Elementer**

In [9]:

# Original matrix A
A = np.array([[2, 1, -1],
              [-1, 3, 2],
              [0, 2, 1]], dtype=float)

# Elementary matrices
E1 = np.array([[1/2, 0, 0],
               [0, 1, 0],
               [0, 0, 1]])

E2 = np.array([[1, 0, 0],
               [1, 1, 0],
               [0, 0, 1]])

E3 = np.array([[1, 0, 0],
               [0, 2/7, 0],
               [0, 0, 1]])

E4 = np.array([[1, 0, 0],
               [0, 1, 0],
               [0, -2, 1]])

E5 = np.array([[1, -1/2, 0],
               [0, 1, 0],
               [0, 0, 1]])

E6 = np.array([[1, 0, 0],
               [0, 1, 0],
               [0, 0, 7]])

E7 = np.array([[1, 0, 0],
                [0, 1, -3/7],
                [0, 0, 1]])

E8 = np.array([[1, 0, 5/7],
                [0, 1, 0],
                [0, 0, 1]])

# Full product of elementary matrices (order matters!)
EA = E8 @ E7 @ E6 @ E5 @ E4 @ E3 @ E2 @ E1 @ A
EA

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Mencari Inverse

## a) Jika invertible

In [26]:
A = np.array([[1,2,3], [2,5,3], [1,0,8]])
inverse_matriks(A)

Inverse matriks:
[[1 2 3]
 [2 5 3]
 [1 0 8]]


## b) Jika Singular

In [27]:
A = np.array([[1,6,4], [2,4,-1], [-1,2,5]])
inverse_matriks(A)

Tidak bisa di inverse karena Singular matrix


In [45]:
A = np.array([[1,2,3], [2,5,3], [1,0,8]])
E1 = np.array([
    [1, 0, 0],
    [-2, 1, 0],
    [0, 0, 1]
], dtype=float)

E2 = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [-1, 0, 1]
], dtype=float)

E3 = np.array([
    [1, -2, 0],
    [0,  1, 0],
    [0,  0, 1]
], dtype=float)

E4 = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [0, 2, 1]
], dtype=float)

E5 = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, -1]
], dtype=float)

E6 = np.array([
    [1, 0, -9],
    [0, 1,  0],
    [0, 0,  1]
], dtype=float)

E7 = np.array([
    [1, 0, 0],
    [0, 1, 3],
    [0, 0, 1]
], dtype=float)

b1 = np.array([
    [4],
    [5],
    [9]
], dtype=float)
b2 = np.array([
    [1],
    [6],
    [-6]
], dtype=float)

B = np.hstack((b1, b2))

# Example: multiply them to get A^{-1}
A_inv = E7 @ E6 @ E5 @ E4 @ E3 @ E2 @ E1 
print(A_inv @ B)

[[-40.  16.   9.]
 [ 13.  -5.  -3.]
 [  5.  -2.  -1.]]


In [47]:
B

array([[ 4.,  1.],
       [ 5.,  6.],
       [ 9., -6.]])

In [48]:
print(A_inv @ B)

[[ 1.  2.]
 [ 0.  1.]
 [ 1. -1.]]
