In [6]:
import numpy as np
import sympy as sp
import matplotlib.pyplot as plt

%matplotlib widget

In [11]:

def show_equations(A, b):
    """
    Display the system Ax = b as symbolic equations using SymPy.
    """
    n, m = A.shape
    x = sp.symbols(f'x1:{m+1}')  # creates (x1, x2, ..., xm)
    equations = []

    for i in range(n):
        lhs = sum(A[i, j] * x[j] for j in range(m))
        rhs = b[i, 0]
        equations.append(sp.Eq(lhs, rhs))

    print("System of equations:")
    for eq in equations:
        display(eq)

    A = sp.Matrix(A)
    b = sp.Matrix(b)

    # Build augmented matrix
    Ab = A.row_join(b)

    print("Augmented matrix form [A | b]:")
    display(Ab)

def show_matrix(A):
    """
    Display the system Ax = b as symbolic equations using SymPy.
    """
    n, m = A.shape
    A = sp.Matrix(A)

    display(A)

def inverse_matrix(A):
    has_inverse = np.linalg.det(A)
    if has_inverse:
        return np.linalg.inv(A)
    else:
        return "Matrix is singular and does not have an inverse."

# **Matriks sebagai hasil dari Multiplikasi Produk Elementer**

In [8]:

# Original matrix A
A = np.array([[2, 1, -1],
              [-1, 3, 2],
              [0, 2, 1]], dtype=float)

# Elementary matrices
E1 = np.array([[1/2, 0, 0],
               [0, 1, 0],
               [0, 0, 1]])

E2 = np.array([[1, 0, 0],
               [1, 1, 0],
               [0, 0, 1]])

E3 = np.array([[1, 0, 0],
               [0, 2/7, 0],
               [0, 0, 1]])

E4 = np.array([[1, 0, 0],
               [0, 1, 0],
               [0, -2, 1]])

E5 = np.array([[1, -1/2, 0],
               [0, 1, 0],
               [0, 0, 1]])

E6 = np.array([[1, 0, 0],
               [0, 1, 0],
               [0, 0, 7]])

E7 = np.array([[1, 0, 0],
                [0, 1, -3/7],
                [0, 0, 1]])

E8 = np.array([[1, 0, 5/7],
                [0, 1, 0],
                [0, 0, 1]])

# Full product of elementary matrices (order matters!)
EA = E8 @ E7 @ E6 @ E5 @ E4 @ E3 @ E2 @ E1 @ A
EA

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Mencari Inverse

## a) Jika invertible

In [12]:
A = np.array([[1,2,3], [2,5,3], [1,0,8]])
inverse_matrix(A)

array([[-40.,  16.,   9.],
       [ 13.,  -5.,  -3.],
       [  5.,  -2.,  -1.]])

## b) Jika Singular

In [14]:
A = np.array([[1,6,4], [2,4,-1], [-1,2,5]])
inverse_matrix(A)

'Matrix is singular and does not have an inverse.'

## c) Menggunakan produk elementer

In [15]:
A = np.array([[1,2,3], [2,5,3], [1,0,8]])
E1 = np.array([
    [1, 0, 0],
    [-2, 1, 0],
    [0, 0, 1]
], dtype=float)

E2 = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [-1, 0, 1]
], dtype=float)

E3 = np.array([
    [1, -2, 0],
    [0,  1, 0],
    [0,  0, 1]
], dtype=float)

E4 = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [0, 2, 1]
], dtype=float)

E5 = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, -1]
], dtype=float)

E6 = np.array([
    [1, 0, -9],
    [0, 1,  0],
    [0, 0,  1]
], dtype=float)

E7 = np.array([
    [1, 0, 0],
    [0, 1, 3],
    [0, 0, 1]
], dtype=float)

b1 = np.array([
    [4],
    [5],
    [9]
], dtype=float)
b2 = np.array([
    [1],
    [6],
    [-6]
], dtype=float)

B = np.hstack((b1, b2))

# Example: multiply them to get A^{-1}
A_inv = E7 @ E6 @ E5 @ E4 @ E3 @ E2 @ E1 
print(A_inv)

[[-40.  16.   9.]
 [ 13.  -5.  -3.]
 [  5.  -2.  -1.]]


# **Mencari Solusi dari Sistem Persamaan Linear**

$x = A^{-1}B$

In [16]:
print(A_inv @ B)

[[ 1.  2.]
 [ 0.  1.]
 [ 1. -1.]]


In [38]:
A = np.array(
    [
        [-2,  0,  1],
        [ 0, -1, -1],
        [ 1,  1, -4]
    ]
)

A_inv = inverse_matrix(A)
print(A_inv)
print()

b = np.array([
    [4, 3, 2, 1],
    [6, 7, 8, 9],
    [1, 3, 7, 9],
])
print(f"x: {A_inv @ b}")


[[-0.55555556 -0.11111111 -0.11111111]
 [ 0.11111111 -0.77777778  0.22222222]
 [-0.11111111 -0.22222222 -0.22222222]]

x: [[-3.         -2.77777778 -2.77777778 -2.55555556]
 [-4.         -4.44444444 -4.44444444 -4.88888889]
 [-2.         -2.55555556 -3.55555556 -4.11111111]]


In [50]:
A = np.array(
    [
        [-6,  0,  0],
        [ 0,  3,  0],
        [ 0,  0,  5]
    ]
)
A @ A @ A

array([[-216,    0,    0],
       [   0,   27,    0],
       [   0,    0,  125]])

In [47]:
25/9

2.7777777777777777